### ISSUE TITLE
persian number

### ISSUE THREAD

**Issue by J-Arji** [graycampbell/GCCalendar#19]
how can add persian number ?

**Comment by graycampbell** [comment]
I'm afraid I don't fully understand your question. Could you elaborate more on what exactly you're looking to accomplish?

**Comment by J-phantom** [comment]
ok sorry 
i want change number showing from [1,2,3,4,5,6,7,8,9,0] to [۱.۲.۳.۴.۵.۶.۷.۸.۹.۰]
 and
how  can change dateFormatter to jalali and show  in calendar

**Comment by J-phantom** [comment]
pleas look at picture  
![unnamed](https://cloud.githubusercontent.com/assets/11584951/14471523/defe3c14-00a3-11e6-86b6-083cdd129d5b.png)

**Comment by graycampbell** [comment]
At the moment, there isn't a way to specifically set the calendar that is being used. The same thing goes for the date formatter.

I'll have to look into adding proper support for different calendars with different date formatters.

**Comment by J-phantom** [comment]
yeah .thanks

**Comment by graycampbell** [comment]
#21 This should be fixed as of Version 2.0.0.
