### ISSUE TITLE
Can i place custom view under every day view?

### ISSUE THREAD

**Issue by mecid** [graycampbell/GCCalendar#20]

**Comment by graycampbell** [comment]
There isn't anything built in right now that would allow you to place a custom view under each day view. I'm not sure if I will add it as a feature, but you're more than welcome to fork the repository and add it yourself if you would like.

Just out of curiosity - what kind of custom view are you trying to place under each day view? What visual effect are you trying to create?

**Comment by mecid** [comment]
I am using JTAppleCalendar for now.
https://github.com/patchthecode/JTAppleCalendar
