### ISSUE TITLE
Not works correctly if first day of week is not Sunday

### ISSUE THREAD

**Issue by blkshdw** [graycampbell/GCCalendar#24]
Hi! Your calendar is great, but it seems that it only supports regions where the first weekday is Sunday. If I set my region, for example, to Russia, where the first day of week is Monday, the calendar(week display mode) crashes.

**Comment by graycampbell** [comment]
Thanks for bringing this to my attention. I'll look into it when I get a chance.

**Comment by graycampbell** [comment]
I've looked into this and have been able to replicate the problem, but I haven't had a chance to go about fixing it yet. It may take me some time, but I'll post updates to this issue as I go along.

**Comment by graycampbell** [comment]
#26 This should be fixed now - [Version 2.1.1](https://github.com/graycampbell/GCCalendar/releases/tag/2.1.1).

All you have to do is update your pod to the latest version of GCCalendar. If you find any other bugs related to this problem, feel free to reopen this issue.

Thanks again for bringing this to my attention.

**Comment by haemi** [comment]
for me the app crashes with an IndexOutOfBounds if the device is set to a region with first day = monday... latest Pod.

**Comment by graycampbell** [comment]
Would you be able to tell me what exact settings your device was using? What region, calendar, etc.? Perhaps even a screenshot of the error if possible? Thanks.

**Comment by graycampbell** [comment]
#32 This should be fixed as of [Version 2.2.1](https://github.com/graycampbell/GCCalendar/releases/tag/2.2.1)

**Comment by graycampbell** [comment]
#32 This should be fixed as of [Version 2.2.1](https://github.com/graycampbell/GCCalendar/releases/tag/2.2.1)
