### ISSUE TITLE
GCCalendarView.currentMonthStartDate returns wrong Date

### ISSUE THREAD

**Issue by srgzah** [graycampbell/GCCalendar#31]
Hi.
For my time zone (UTC+3), the method `func currentMonthStartDate(fromDate date: Date) -> Date` always returns the last day of the previous month.

As a result, the method  `calendarView(_:didSelectDate:inCalendar:)` returns a date a day less than it displays.

I fixed it this way:
```
var components = self.configuration.calendar.dateComponents([.hour, .minute, .day, .month, .year], from: date)
components.day = 1
return self.configuration.calendar.date(from: components)!
```

**Comment by graycampbell** [comment]
Thanks for letting me know, and thanks for offering a solution - I really appreciate it. I'll have this fixed soon.

**Comment by graycampbell** [comment]
I've looked into this, and there doesn't appear to be anything for me to change. Even though the Date objects returned by those methods appear to contain the wrong date, they actually don't. Dates are stored using a specific time zone not constrained by the time zone of the current device. Therefore, if you want the date displayed to the user to reflect the current time zone, you need to use the correct date formatter.

To see what I'm talking about, clone the repository, open the workspace, and navigate to the CalendarViewController.swift file in the GCCalendarDemo project. In the `calendarView(_:didSelectDate:inCalendar:)` method, change the date formatter template to `"dd MMMM yyyy"` and then run the project in the simulator. The correct date will be displayed in the navigation bar even if the Date object passed to the method appears to be the wrong date.
