### ISSUE TITLE
First Day As Monday Manually Setting For GCCalendar WeekView

### ISSUE THREAD

**Issue by khaskheli24** [graycampbell/GCCalendar#33]
I am Facing Difficulty To Set A Week Start From Monday,  it is difficult for me, i set calendar Local A country where week start from monday but it not works. so please help, i have latest code.

**Comment by graycampbell** [comment]
There is a GCCalendarViewDelegate method for providing the calendar view with a specific calendar. Setting the locale on that calendar should work. The below code works for me.

```
func calendar(calendarView: GCCalendarView) -> Calendar {

    var calendar = Calendar.current
    calendar.locale = Locale(identifier: “en_ES”)
    
    return calendar
}
```

Let me know if that solves the problem for you.

**Comment by khaskheli24** [comment]
Great! Thanks It Works Perfectly.

**Comment by graycampbell** [comment]
Glad I could help!
