### ISSUE TITLE
Select Specific Date

### ISSUE THREAD

**Issue by popwarfour** [graycampbell/GCCalendar#35]
How do you programmatically select a specific Date? The only option I can find is the today() function.

**Comment by graycampbell** [comment]
There isn't currently a way to programmatically select a specific Date, but it probably wouldn't be too difficult to implement, so I'll look into adding it as a feature.

**Comment by graycampbell** [comment]
It's turning out to be a pretty quick process, so no need to do it yourself, but thanks for the offer! I'll leave another comment here when it's pushed and ready to use.

**Comment by popwarfour** [comment]
amazing, thank you!

**Comment by graycampbell** [comment]
[Version 2.3.0](https://github.com/graycampbell/GCCalendar/releases/tag/2.3.0) has been published. Feel free to reopen this issue if you come across any problems. Thanks!
