### ISSUE TITLE
Incorrect date after year change

### ISSUE THREAD

**Issue by popwarfour** [graycampbell/GCCalendar#37]
Try manually setting the date to something like 1/2/2018 using week mode. currentWeekDates(fromDate date: Date) gets called with the correct custom date passed in. However, the startDate calculated within that method is 12/30/2018 instead of 12/30/2017 causing the week view to show the dates for 2019 instead.

**Comment by graycampbell** [comment]
Interesting - I guess I never considered this scenario. Thanks for letting me know.

**Comment by graycampbell** [comment]
This should be fixed as of [Version 2.3.1](https://github.com/graycampbell/GCCalendar/releases/tag/2.3.1).

**Comment by popwarfour** [comment]
That was fast, thank you very much my friend!
