### ISSUE TITLE
Date issue in didselectDate

### ISSUE THREAD

**Issue by kishansuthar** [graycampbell/GCCalendar#38]
In GCCalendar didSelectDate method selected date is  25/4/18  but get date is 24/4/18 .. how solve this problem...??

**Comment by kishansuthar** [comment]
How to set maximum and minimum range date in GCCalendar..??

**Comment by graycampbell** [comment]
You can disable past dates, but you can't set a date range for the calendar to display as of right now.

If this is a feature you'd like to see implemented, it would be helpful if you could open a new issue specifically requesting date ranges as a feature. If you don't have any other questions related to your question about `didSelectDate`, then I would like to close this issue and discuss date ranges on a new one. It's just helpful for me to keep unrelated issues separate so I can keep track of them better.
